services:
  # SQL Server service
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - prodData:/var/opt/mssql

      
  # Redis service
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 10s
      retries: 5

  # gestionSite service
  gestionsite:
    build:
      context: .  
      dockerfile: gestionSite/Dockerfile   
    image: mechaymen/gestionsite:latest
    container_name: gestionsite
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=gestionSiteProd;User Id=sa;Password=YourStrongPassword123;Encrypt=False;TrustServerCertificate=True
      - RabbitMQ__Host=rabbitmq
      - Redis__Host=redis
    ports:
      - "5150:8080"
    depends_on:
      sqlserver:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network
    volumes:
      - ./gestionSite:/src/gestionSite  
      - ./Shared.Messaging:/src/Shared.Messaging

# gestionEmployer service
  gestionemployer:
    build:
      context: .
      dockerfile: gestionEmployer/Dockerfile
    image: mechaymen/gestionemployer:latest
    container_name: gestionemployer
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=gestionEmployerProd;User Id=sa;Password=YourStrongPassword123;Encrypt=False;TrustServerCertificate=True
      - RabbitMQ__Host=rabbitmq
      - Redis__Host=redis
    ports:
      - "5097:8080"
    depends_on:
      - sqlserver
      - rabbitmq
      - redis
    networks:
      - app-network
    volumes:
      - ./gestionEmployer:/src/gestionemployer  

  # Auth service
  auth:
    build:
      context: .
      dockerfile: Auth/Dockerfile
    image: mechaymen/auth:latest
    container_name: auth
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=authProd;User Id=sa;Password=YourStrongPassword123;Encrypt=False;TrustServerCertificate=True
      - RabbitMQ__Host=rabbitmq
      - Redis__Host=redis
    ports:
      - "5181:8080"
    depends_on:
      - rabbitmq
    networks:
      - app-network
    volumes:
      - ./Auth:/src/auth

  # gestionUtilisateur service
  gestionutilisateur:
    build:
      context: . 
      dockerfile: gestionUtilisateur/Dockerfile
    image: mechaymen/gestionutilisateur:latest
    container_name: gestionutilisateur
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=gestionUtilisateurProd;User Id=sa;Password=YourStrongPassword123;Encrypt=False;TrustServerCertificate=True
      - RabbitMQ__Host=rabbitmq
      - Redis__Host=redis
    ports:
      - "5255:8080"
    depends_on:
      - sqlserver
      - rabbitmq
      - redis
    networks:
      - app-network
    volumes:
      - ./gestionUtilisateur:/src/gestionutilisateur

  # gestionEquipe service
  gestionequipe:
    build:
      context: .
      dockerfile: gestionEquipe/Dockerfile
    image: mechaymen/gestionequipe:latest
    container_name: gestionequipe
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=gestionEquipeProd;User Id=sa;Password=YourStrongPassword123;Encrypt=False;TrustServerCertificate=True
      - RabbitMQ__Host=rabbitmq
      - Redis__Host=redis
    ports:
      - "5108:8080"
    depends_on:
      sqlserver:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network
    volumes:
      - ./gestionEquipe:/src/gestionequipe

  # gestionReservation service
  gestionreservation:
    build:
      context: . 
      dockerfile: gestionReservation/Dockerfile
    image: mechaymen/gestionreservation:latest
    container_name: gestionreservation
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=gestionReservationProd;User Id=sa;Password=YourStrongPassword123;Encrypt=False;TrustServerCertificate=True
      - RabbitMQ__Host=rabbitmq
      - Redis__Host=redis
    ports:
      - "5169:8080"
    depends_on:
      - sqlserver
      - rabbitmq
      - redis
    networks:
      - app-network
    volumes:
      - ./gestionReservation:/src/gestionreservation

    # serviceMail service
  servicemail:
    build:
      context: . 
      dockerfile: serviceMail/Dockerfile
    image: mechaymen/servicemail:latest
    container_name: servicemail
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__Host=redis
    ports:
      - "5193:8080"
    depends_on:
      - redis
    networks:
      - app-network

  # chatEtInvitation service
  chatetinvitation:
    build:
      context: .
      dockerfile: chatEtInvitation/Dockerfile
    image: mechaymen/chatetinvitation:latest
    container_name: chatetinvitation
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=chatEtInvitationProd;User Id=sa;Password=YourStrongPassword123;Encrypt=False;TrustServerCertificate=True
      - RabbitMQ__Host=rabbitmq
      - Redis__Host=redis
    ports:
      - "5270:8080"  
    depends_on:
      sqlserver:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - app-network
    volumes:
      - ./chatEtInvitation:/src/chatetinvitation

# API Gateway 
  apigateway:
    build:
      context: . 
      dockerfile: ApiGateway/Dockerfile
    image: mechaymen/apigateway:latest
    container_name: apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5010:8080"  
    depends_on:
      - gestionsite
      - gestionemployer
      - gestionreservation
      - gestionequipe
      - servicemail
      - gestionutilisateur
      - auth
      - chatetinvitation
    networks:
      - app-network
    volumes:
      - ./ApiGateway:/src/apigateway  

  angular-app:
    build:
      context: .
      dockerfile: angular/Dockerfile
    image: mechaymen/angularapp:latest
    container_name: angular-app
    environment:
      - NODE_ENV=development
    ports:
      - "4300:4200"
    networks:
      - app-network
    volumes:
      - /app/node_modules

volumes:
  prodData:

networks:
  app-network:
    driver: bridge